global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s

alerting:
    alertmanagers:
        - static_configs:
            - targets: []
          scheme: http
          timeout: 10s
          api_version: v2

scrape_configs:
    - job_name: iperf3
      honor_timestamps: true
      scrape_interval: 60s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets:
            - iperf3_exporter:8080      