{
 "title": "Internet Speed",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "measurement_source",
    "label": "Source",
    "query": {
     "query": "label_values(speeder_runs_counter,source_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speeder_download_speed{source_name=\"$measurement_source\"}",
     "legendFormat": "Download Speed"
    },
    {
     "expr": "speeder_upload_speed{source_name=\"$measurement_source\"}",
     "legendFormat": "Upload Speed"
    }
   ]
  },
  {
   "title": "Download Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speeder_download_latency{source_name=\"$measurement_source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "speeder_download_speed{source_name=\"$measurement_source\"}",
     "legendFormat": "Download Speed"
    },
    {
     "expr": "speeder_upload_speed{source_name=\"$measurement_source\"}",
     "legendFormat": "Upload Speed"
    }
   ]
  },
  {
   "title": "Download Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speeder_download_latency{source_name=\"$measurement_source\"}",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}