name: Build Release

on:
  push:
    tags:
      - "*"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux x64, os: ubuntu-22.04, arch: linux-x64 }
          - { name: Linux arm64, os: ubuntu-22.04, arch: linux-arm64 }
          - { name: Windows x86, os: windows-2022, arch: win-x64 }
          - { name: macOS, os: macos-15, arch: osx-x64 }
          - { name: macOS ARM, os: macos-15, arch: osx-arm64 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
      
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet publish --no-restore --runtime ${{ matrix.platform.arch }} -c Release -o out/ -p:VersionPrefix=${{ github.ref_name }}
      
      - name: Rename Artifact (Linux / macOS )
        if: matrix.os != 'windows-2022'
        run: "[ -f out/Speeder ] && mv out/Speeder out/speeder-${{ matrix.platform.arch }}"

      - name: Rename Artifact (Windows)
        if: matrix.os == 'windows-2022'
        run: "Move-Item out/Speeder.exe out/Speeder-${{ matrix.platform.arch }}.exe -Force -ErrorAction SilentlyContinue"

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: exe
          if-no-files-found: ignore
          retention-days: 7
          path: |
            out/Speeder-${{ matrix.platform.arch }}
            out/Speeder-${{ matrix.platform.arch }}.exe
  release:
    name: "Create Release"
    needs: [ build ]
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v4
        with:
          draft: false
          prerelease: false
          release_name: "v${{ github.ref_name }}"
          tag_name: ${{ github.ref }}
      
      - name: Get All Artifacts
        uses: actions/download-artifact@v4
      
      - name: Attach Linux x64 Artifact
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./speeder-linux-x64
          asset_name: speeder-linux-x64
          asset_content_type: application/octet-stream
      
      - name: Attach Linux amd64 Artifact
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./speeder-linux-amd64
          asset_name: speeder-linux-amd64
          asset_content_type: application/octet-stream
      
      - name: Attach Windows x64 Artifact
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./speeder-windows-x64.exe
          asset_name: speeder-windows-x64.exe
          asset_content_type: application/octet-stream
      
      - name: Attach macOS x64 Artifact
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./speeder-osx-x64
          asset_name: speeder-osx-x64
          asset_content_type: application/octet-stream
      
      - name: Attach macOS arm64 Artifact
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./speeder-osx-arm64
          asset_name: speeder-osx-arm64
          asset_content_type: application/octet-stream